### ISSUE TITLE
[Hyperion] [BE] Getting error on updating the chart if it is an external chart which is deployed from terminal using helm install

### ISSUE THREAD

**Issue by manish-agrawal-ai** [devtron-labs/devtron#1270]
**Chart name** : bitnami/apache

<img width="1361" alt="Screenshot 2022-02-24 at 1 16 56 PM" src="https://user-images.githubusercontent.com/85211469/155480885-fc209e61-7984-42c3-bd8c-f1311ebf4f43.png">

Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Proposed solution**
On updating the EA release check conditionally on UI whether is external or internal, If it is internal then ask for linking (repo/version/chart/values) etc.. and save it in DB.

**Comment by uxarya-d** [comment]
### Proposal

UI Link: https://www.figma.com/file/j7cqlBdhQ47Bo10TLfamGl/?node-id=403%3A737

Show error below chart dropdown if a chart is not linked to the app.
User can select a chart from dropdown to link.
When user opens dropdown, show charts matching with chart name; else show empty state
In dropdown, show option to go to chart repositories (open in new tab) [this will be for all helm apps not specific to external]
The refresh button next to the chart dropdown updates the dropdown with latest data.

**After a chart is selected:**
Show chart version and values dropdowns

Chart version: Select version used in helm app if available; otherwise select latest version

Chart values: In dropdown, show app name in existing section; don't show chart version. (to discuss)
After the app is deployed using a chart, the selected item will be moved to deployed section; show chart version.

**BUG:**
Show README for selected chart; Currently, it shows Readme for chart used for deployment not the one selected

**Other:**
Chart repo add toast text change

**Comment by manish-agrawal-ai** [comment]
Tech doc : 

https://docs.google.com/document/d/16sHjjIDA3jcsghVTjqyS_QmK-x6qgNFPEgVi_7I3LvM/edit
