### ISSUE TITLE
Git-sensor continuously polling data for repos even if app has a linked-ci

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#1709]
**Describe the bug**

We have created so many linked pipelines for different applications. In those applications, we don't have any other ci-pipeline configured, and when we checked with git-sensor logs it was continuously polling data for the git-material we have provided in the child application.

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. Create a devtron application(parent) with all the configurations.
2. Create another devtron application(child) with the linked pipeline option only and use any other repo for your git-material.
3. Now check the git-sensor logs.

**Expected behavior**

Ideally, it shouldn't fetch the details for those applications that are only using the linked pipeline option.

AB#288

**Comment by prakash100198** [comment]
This bug is invalid. 
Reason:- We are not polling git commits for the app with all linked CI-Pipeline as per our code, only when the git material in child application has been used in one or more ci-pipeline then only our code is polling the data for that git material else, it's not. Hence this bug is invalid.

Tests:- I've verified it from our code and from logs also. Secondly, I've also checked the latest commits that are saved in the git-sensor by exec-ing into gitsensor.
