### ISSUE TITLE
Getting yaml parse error during update and deploy any helm chart

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#2178]
When in values.yaml of any helm apps contain extra comments so getting yaml parse error during deploy. 

Checklist:

* [X] I've searched in the docs and FAQ for my answer
* [X] I've included steps to reproduce the bug.

**Describe the bug**

When we have extra comments in values.yaml of helm apps with the default values , during click on deploy or update and deploy of charts it through error as in screenshot .  
**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. try to deploy prometheus stack or click on update and deploy if it is already deployed using charts from UI.

**Expected behavior**

It should able to update and deploy 

**Current behavior** 

Getting yaml parse error during update and deploy

**Screenshots**
![Screenshot (152)](https://user-images.githubusercontent.com/99399155/185050265-10934287-012e-4b5c-be87-2c908e4d0d88.png)

**Logs**
 
```
Paste any relevant application logs here.
```

AB#102

**Comment by sohel-rp** [comment]
This issue was with the limitation introduced in the latest version of YAML. For now, reverted the version & will analyze this further in [#2214](https://app.zenhub.com/workspaces/devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/2214).

PR - https://github.com/devtron-labs/dashboard/pull/471
