### ISSUE TITLE
Bug: Multiple vulnerabilities detected on devtroncd & argo namespace

### ISSUE THREAD

**Issue by wali97** [devtron-labs/devtron#2737]
### 📜 Description

I've deployed devtron v0.6.8 over a private GKE cluster and enabled the gke security posture feature from GCP and after scanning it showed more than 1k+ vulnerabilites in devtroncd namespace itself and out of which 600 are medium,150 high & 15 critical vulnerabilites which imposes a major threat to the overall cluster & due to this it wouldn't be a good option to deploy devtron in prod envt. 

### 👟 Reproduction steps

Configure GKE cluster and deploy devtron over it and turn the security posture feature on.

### 👍 Expected behavior

No or very less vulnerabilities must've occured.

### 👎 Actual Behavior

Attached is the overview of the vulnerabilites found.

![image](https://user-images.githubusercontent.com/76784894/206125535-1cad6bee-756e-4f7c-a61b-165a6be9f424.png)

### ☸ Kubernetes version

GKE v1.23

### Cloud provider

GCP

### 🌍 Browser

Chrome

### ✅ Proposed Solution

To fix this,update the library packages being used in devtron and disabling pod containers to run as root in argo workflow-controller pod.
![image](https://user-images.githubusercontent.com/76784894/206126114-949a3fa0-652a-409e-b56f-335f556d1aa6.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by pghildiyal** [comment]
Hi @wali97 Thanks for reporting the issue. We have a responsible disclosure policy at https://github.com/devtron-labs/devtron#bug-vulnerability-reporting. 
Also the it run in privilege mode because it uses DIND which requires privilege access. It is the one which is used by Jenkins agent also and provided by other providers. 

Though they are considered not root-safe they are considered valuable in the trusted workload environment. You can read more about it at https://brauner.io/2019/02/12/privileged-containers.html

And since Devtron installation is not multi-tenant, its installed within your infrastructure running workloads approved by your team it is a trusted workload. Additionally these are temporary isolated nodes and therefore can be further hardened.

Having said that we are also exploring few mechanisms to do it without DIND so that we dont need privileged access for eg moving to using emissary on argo workflos. Will open a separate issue for that. 

Please send us the details of the vulnerabilities at security@devtron.ai.

**Comment by prakarsh-dt** [comment]
Resolved by #4839
