### ISSUE TITLE
Bug: Unexpected end of json input while adding new permissions for users

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#3266]
### 📜 Description

Unexpected end of json input while adding new permissions for users

### 👟 Reproduction steps

Add some permissions for users by adding them as new users everytime with same email ids

### 👍 Expected behavior

Permissions for the users who are existing should get merged with existing permissions

### 👎 Actual Behavior

Keeps throwing error sometimes and doesn't update the user

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kartik-579** [comment]
RCA: Entity and AccessType of devtron apps was being wrongly updated when merging old and new role filters in createUser request (but for existing user). This was causing the code to fetch default role and policies for corrupt combination of entity and accessType due to which we were getting empty default policies and role. Further, empty policies and roles resulted into unmarshal error - unexpected end of json input.
