### ISSUE TITLE
Bug: Unable to scroll on about cluster page.

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#3734]
### 📜 Description

when the cluster detail file is large then the scrolling is not working.

### 👟 Reproduction steps

go to clusters and select cluster and edit cluster details in about cluster. and save it .
then do scrolling.
<img width="1429" alt="Screenshot 2023-08-07 at 3 02 39 PM" src="https://github.com/devtron-labs/devtron/assets/122791251/bc4d7567-13e9-4be1-902c-ec24d4f35f12">

### 👍 Expected behavior

scroll should works.

### 👎 Actual Behavior

scroll is not working.

### ☸ Kubernetes version

1.25

### Cloud provider

<details>
any
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

error is in dashboard.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by ShashwatDadhich** [comment]
**RCA** 
 1) _Introduced_ - This bug was introduced in the feature where we had to add app description and modify the UI for jobs description. The UI should look same as that of About Cluster page.
 
 2) _Reason_ - The resaon for this bug was negligence and not verifying the test cases. Since the about cluster page was previously working, it was assumed that it will work the same now also.
 
 3) _Action Item_ - I will first verify all the test cases and then do the testing. I will not assume that if a feature was already working earlier, it will work after changes also.
