### ISSUE TITLE
Bug: env variables are not reading correctly 

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#3735]
### 📜 Description

1. In pre-deploy/post deploy & pre-ci and post-ci  if we write any export command like -:
     **_export product_name=devtron_**

it's not passing correctly in CI_CD_EVENT environment  variable . 
Basically the issue was with  _**=**_ this equals symbol .

NOTE
Their is no issue with the script .It runs perfectly .But the issue is with the env variables in which we put all the data .
If some one reading the env then their is a issue  because the 
_**env  > .all_env**_
then their is a issue  because the **CI_CD_EVENT** variable having invalid data .or non ending value

### 👟 Reproduction steps

just try this step in pre/post cd of any pipeline and you will see the CI_CD_EVENT variable have a non-ending string value or inavlid value.
Try to print all the env variables .
**env**

### 👍 Expected behavior

it should be worked fine .

### 👎 Actual Behavior

not working .Due to this when i read env variables and doing some thing then not able to do

### ☸ Kubernetes version

1.25

### Cloud provider

<details>

</details>
aws

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4818

**Comment by kartik-579** [comment]
RCA: this was happening due to logic of getting env variable key-value pair. we used to split whole string from arg by "=" separator and use the first two indexes as our key and value. In cases where value contained "=", the value was getting split and was being partially set. It was reported when one user's script in pre-cd started breaking since before the scripts were run as raw scripts and now they are being run with plugin support mechanism.
