### ISSUE TITLE
Bug: Overridden configMaps remain in hanging state if deleted from base deployment template

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#3859]
### 📜 Description

Overridden configMaps remain in a hanging state if deleted from the base deployment template. This happens only in the case of cloned applications.

### 👟 Reproduction steps

1. Create an application let's say `app1`
2. Create a configMap in the base deployment template. 
3. Override the configMap in env overrides.
4. Create an application let's say `app2` cloned from `app1`
5. Delete the configMap from the base deployment template.
6. The configMap in environment overrides remains in an `inheriting` state and can not be deleted. It remains hanging.

### 👍 Expected behavior

The configMap's state should have been `env` rather than inheriting. And the option to delete the overridden configMap should have been present.

### 👎 Actual Behavior

The configMap in environment overrides remains in `inheriting` state and can not be deleted. It remains hanging.

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5313

**Comment by prakash100198** [comment]
This was a production bug, when we clone an application with global cmcs and when it's overriden in an env, so when we delete the parent global cmcs, the env cmcs from which it was overriden, it should now be tagged as ENV not inheriting in cloned applications, now the default state for global variable for a cmcs is set as true(in case of cloned app), but in db by default it's stored as false, whether a cmcs is global or not we handle it with some logic at service layer. Hence in this case when we delete the global cmcs in the cloned app, since the global = true and overriden= false, it persists in inheriting state since front-end provides inheriting tag when global = true and overriden=false. but in normal application when we delete the global cmcs the fetch api in env section of cmcs has global=false and overriden=false which is correct.
