### ISSUE TITLE
Bug: git sensor is not able to fetch latest commits 

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#3881]
### 📜 Description

It bugs out when trying to fetch the latest commits. There is no error in UI but could see below error in git-sensor logs :
`error in git cli operation","msg":"fatal: detected dubious ownership in repository`
`error in updating repository","err":"exit status 128`

### 👟 Reproduction steps

1. This is happening in all the applications with latest release.
Note : It'll not happen in new applications or newly created workflows.

### 👍 Expected behavior

CI should have fetched the latest commits

### 👎 Actual Behavior

CI is not able to fetch the latest commits

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5434

**Comment by iamayushm** [comment]
**RCA** 
Git in it's newer versions checks if the current user is the owner of the git repository folder, and will produce "detected dubious ownership" error if the current user is not the owner. We have recently updated our git version for shallow cloning due to which old git materials saved in devtron as root user started throwing error when devtron User was running git fetch.

Reproduced this issues by saving git material as root User using old git sensor image (when we use to run container as root user) and then fetching commits as devtron User.
