### ISSUE TITLE
Bug: Cannot have envs with the same name on different clusters

### ISSUE THREAD

**Issue by rangoku** [devtron-labs/devtron#4260]
### 📜 Description

Cannot have envs with the same name on different clusters

### 👟 Reproduction steps

1. Connect at least 2 clusters
2. Create env with any name on one of the clusters
3. Try creating env with the same name on another cluster

### 👍 Expected behavior

It should allow us to have envs with the same name on different clusters

### 👎 Actual Behavior

An error message "environment already exists" occurs. 

### ☸ Kubernetes version

v1.27.3-gke.100

### Cloud provider

GCP

### 🌍 Browser

Opera

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6850

**Comment by prakarsh-dt** [comment]
Hi @rangoku,

This is an expected behavior as environments on Devtron are unique.

So if you want to have a namespace `dev` on `cluster-1` as well as `cluster-2`. On Devtron you can add the environment as cluster1-dev and cluster2-dev while you can map both these environments to the same namespace `dev` in the respective clusters.
<img width="788" alt="Screenshot 2023-11-21 at 12 35 51 PM" src="https://github.com/devtron-labs/devtron/assets/71125043/58be7d2a-6bb8-401e-947e-4a95d3eb949f">

This was done for simplicity purpose as it would otherwise be even more complex to manage accesses for the users as it will introduce an additional value `Clusters` to be selected for giving access to the users.
