### ISSUE TITLE
Bug:  Kubelink is unable to create a new release with a user-defined reference chart version after saving it

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#4768]
### 📜 Description

A Devtron application is deployed using Helm. Previously, the CD pipeline utilized the 4.14 chart version. Now, when attempting to update the chart version to 4.18 via the UI, we receive confirmation that the chart version was saved successfully. However, we are not observing the 4.18 release when we trigger deployment.

```
 helm ls -n test-stage | grep test-xxxxx  
test-xxxxx         ucp-stage       237             2024-01-19 08:01:22.055080376 +0000 UTC deployed        ucp-app-starfleet-aws-4.14.1    
```

### Criticality

P0 - Critical/Blocking

### Impact on Enterprise

ENT-DEY

### 👟 Steps to replicate the Issue

NA

### 👍 Expected behavior

NA

### 👎 Actual Behavior

NA

### ☸ Kubernetes version

1.25

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8826

**Comment by prakash100198** [comment]
Basically the issue is that, when user has changed the reference chart version from 4.14 to 4.18 and goes to deploy with the same chart, then cd trigger is getting failed with an error that ensure HPA version v2beta2 is installed first, which is made in reference template version 4.14, and when we run command helm ls -n test-stage | grep test-xxxxx  it does not create a new release with 4.18 reference values. also 4.18 created HPA v2 version.  

Also the server version was upgraded 2 months back, and this pipeline cd trigger has been failing since 2 months only.
When helm upgrade command is called, helm 3.0 also considers the currently deployed spec, so while running helm template over previous deployment it fails as HPA v2/beta2 is not supported by current server version, since current version only supports v2 of HPA now, hence helm upgrade failing. 

for this to work we deleted all the secrets of all the previous deployments for that app, since all those secrets were created in previous version, (which supported v2beta2 which in not in current server version). After deleting all secrets and triggering cd again solved the issue.
