### ISSUE TITLE
Bug: unable to change the branch in linked CI

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#4974]
### 📜 Description

getting error like `error while updating pipeline` 
in api `orchestrator/app/ci-pipeline/patch` response 
{
    "code": 500,
    "status": "Internal Server Error",
    "errors": [
        {
            "code": "000",
            "internalMessage": "[{error while updating linked pipeline}]",
            "userMessage": "error while updating linked pipeline"
        }
    ]
}

### Affected areas

CI

### Additional affected areas

CD

### Prod/Non-prod environments?

Prod

### Is User unblocked?

Yes

### How was the user un-blocked?

None

### Impact on Enterprise

sp

### 👟 Steps to replicate the Issue

use linked ci and getting error in few pipelines

### 👍 Expected behavior

should able to change branch

### 👎 Actual Behavior

error

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9455

**Comment by iamayushm** [comment]
The user was updating ci pipeline having 11 child pipelines. The issue was due to corrupt data (wrong git material id )present in one of the child pipeline. For linked CI pipeline git material ID should be same as that of parent but in this case it was different.
RCA: The pipeline having corrupt data was created using app create API. In app create api validations on linked pipeline are missing.
