### ISSUE TITLE
Bug: Not able to Delete Applications deployed through Gitops when the cluster is unreachable.

### ISSUE THREAD

**Issue by akshatsinha007** [devtron-labs/devtron#5365]
### 📜 Description

1. When the cluster is unreachable and Gitops deployed applications(Helm as well as Devtron) is deleted from argocd then we are unable to delete the application from DevtronUI even with force delete as the force delete modal keeps coming,we have to manually clear it from the database.

### 👟 Reproduction steps

1.Delete the deployed application from Argocd.
2. Now try deleting it from DevtronUI.

### 👍 Expected behavior

The Application should get deleted from UI

### 👎 Actual Behavior

Throws Delete and Force Delete modal only. Sometimes getting the force delete modal multiple times

### ☸ Kubernetes version

EKS 1.28

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10041

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5364] Bug: Not able to delete Helm charts deployed through no gitops when the cluster is unreachable. (63.33%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5364] Bug: Not able to delete Helm charts deployed through no gitops when the cluster is unreachable. (63.33%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5364] Bug: Not able to delete Helm charts deployed through no gitops when the cluster is unreachable. (63.33%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5364] Bug: Not able to delete Helm charts deployed through no gitops when the cluster is unreachable. (63.33%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5364] Bug: Not able to delete Helm charts deployed through no gitops when the cluster is unreachable. (63.33%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5364] Bug: Not able to delete Helm charts deployed through no gitops when the cluster is unreachable. (63.33%)

**Comment by Casburggraaf** [comment]
I have a similar issue:
I have a cluster that I need to delete but can't because there is an undeletable application. See the screenshots for the errors.
I'm using the latest Devtron version.

<img width="2752" alt="Google Chrome 2024-06-28 14 17 22" src="https://github.com/devtron-labs/devtron/assets/373753/1ab8c4ad-519f-432a-842d-c20bc0747c47">
<img width="905" alt="Google Chrome 2024-06-28 14 17 26" src="https://github.com/devtron-labs/devtron/assets/373753/53f2cdc0-a874-4b9f-9a48-3cd9af2944a9">
<img width="3279" alt="Google Chrome 2024-06-28 14 17 29" src="https://github.com/devtron-labs/devtron/assets/373753/d255bc50-2211-4759-aefe-26dc3167c655">
<img width="750" alt="Google Chrome 2024-06-28 14 17 31" src="https://github.com/devtron-labs/devtron/assets/373753/e153f380-d786-402e-9788-df9689ccd7d8">

**Comment by prakarsh-dt** [comment]
@pawan-59 Can you verify if this still exists

**Comment by satyampsoni** [comment]
This has been fixed!
