### ISSUE TITLE
App metrics enable UX

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#818]
# Summary

App metrics enable UX

AB#424

**Comment by uxarya-d** [comment]
Issues to fix for release:

- [ ] Code editor does not resize horizontally when metrics readme is opened (This hides code if it extends beyond the readme; Find feature of editor is hidden)

- [ ] Metrics not supported error bar > hides code editor

- [ ] Metrics not supported error bar > CSS

- [ ] In app create flow, Deployment template section > [Save & Next] creates wrong URL due to which user is not navigated to workflow editor

- [ ] Clicking on Save and Next button should show a loader inside the button as the action takes time. Currently there's no feedback. (We already have buttons with progress loader, you can use that.)

- [ ] Enable App metrics > Click on Save > toast shows enabled but checkbox becomes unticked after saving. (Also, to be checked in Env Override)

- [ ] Allow override > Enable metrics > Delete override without saving > The state does not reset on deleting override. Expected: This should remove the app metrics readme and show app defaults for yaml and app metrics checkbox.

- [ ] Switch editable yaml position in comparison view

- [ ] Adding keys with default values automatically

- [ ] Env override > Compare with default > Open App metrics readme > Close app metrics readme > Code editor does not resize to full width
